# -*- coding: utf-8 -*-
"""WebsiteCategorizationBERTpipline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKRQN_4GIX4sGDxK9U2Xu6dpjdy4AJXU
"""

!pip install gdown

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import gdown

file_id = '1unzca2u1H_I-GtPAvFGdCesoNBPUCqZs'
url = f'https://drive.google.com/uc?id={file_id}'

# Download the file to your Colab environment
output_file = 'full.csv'
gdown.download(url, output_file, quiet=False)

#read the downloaded CSV file
df = pd.read_csv(output_file)

# verify that the upload was sucessfull
import os
print(os.listdir())

# Import necessary libraries
from transformers import BertTokenizer, BertForSequenceClassification
import torch
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd

data = pd.read_csv(output_file)
data = data.dropna(subset=['content', 'category'])  # Drop rows with missing content or category

# Map categories to numeric labels
categories = sorted(data['category'].unique())
category_to_id = {cat: idx for idx, cat in enumerate(categories)}
data['label'] = data['category'].map(category_to_id)

# Define texts and labels
texts = data['content'].fillna("").values
labels = data['label'].values

# Split the data into training and validation sets
from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

# Define the Dataset class
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer

# Dataset Preparation
class WebsiteDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = self.labels[idx]

        # Tokenize text using BERT tokenizer
        encoding = self.tokenizer.encode_plus(
            text,
            max_length=self.max_len,
            truncation=True,
            padding='max_length',
            add_special_tokens=True,
            return_attention_mask=True,
            return_tensors="pt"
        )
        return {
            'input_ids': encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'label': torch.tensor(label, dtype=torch.long)
        }

# Step 7: Prepare datasets and DataLoaders
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

train_dataset = WebsiteDataset(train_texts, train_labels, tokenizer)
val_dataset = WebsiteDataset(val_texts, val_labels, tokenizer)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

# Step 8: Define the Model
from transformers import BertForSequenceClassification
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased', num_labels=len(categories)
)
model = model.to(device)

# Step 9: Define optimizer and loss function
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
loss_fn = torch.nn.CrossEntropyLoss()

# Training function
def train_model(model, data_loader, optimizer, loss_fn, device):
    model.train()
    total_loss = 0
    for batch in data_loader:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    return total_loss / len(data_loader)  # Return the average loss for the epoch

# Initialize a list to track training losses
training_losses = []

# Train the model
for epoch in range(3):  # Train for 3 epochs
    train_loss = train_model(model, train_loader, optimizer, loss_fn, device)
    training_losses.append(train_loss)  # Save loss for the epoch
    print(f'Epoch {epoch + 1}, Training Loss: {train_loss}')  # Print loss for the epoch

# After training, visualize the loss
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(range(1, len(training_losses) + 1), training_losses, marker='o')
plt.title("Training Loss Across Epochs", fontsize=16)
plt.xlabel("Epoch", fontsize=12)
plt.ylabel("Loss", fontsize=12)
plt.grid(True)
plt.show()

# Step 12: Evaluation function
from sklearn.metrics import classification_report, accuracy_score

def evaluate_model(model, data_loader, device):
    model.eval()
    predictions = []
    true_labels = []
    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            predictions.extend(torch.argmax(logits, dim=1).cpu().numpy())
            true_labels.extend(labels.cpu().numpy())

    return true_labels, predictions

true_labels, predictions = evaluate_model(model, val_loader, device)

# Ensure target_names matches the number of classes
#print(classification_report(true_labels, predictions, target_names=categories))
print("Accuracy:", accuracy_score(true_labels, predictions))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Ensure categories align with predictions and true labels
unique_labels = sorted(set(predictions) | set(true_labels))
adjusted_categories = [categories[label] for label in unique_labels]  # Map back to category names

# Generate confusion matrix
cm = confusion_matrix(true_labels, predictions, labels=unique_labels)

# Display confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=adjusted_categories)

plt.figure(figsize=(100, 100))
disp.plot(cmap='viridis', xticks_rotation=45)
plt.title("Confusion Matrix of Validation Predictions", fontsize=16)
plt.show()

pip install shap

import shap

# Ensure tokenizer and model are set up
from transformers import BertTokenizer, BertForSequenceClassification
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=len(categories))
model = model.eval()  # Ensure model is in evaluation mode

# Initialize SHAP explainer
def predict_proba(inputs):
    """
    Custom function to predict probabilities from tokenized inputs.
    """
    tokenized_inputs = tokenizer(inputs, truncation=True, padding=True, max_length=128, return_tensors="pt")
    with torch.no_grad():
        outputs = model(**tokenized_inputs)
        probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
    return probabilities.cpu().numpy()

explainer = shap.Explainer(predict_proba, tokenizer)

# Generate explanations for a single input
input_text = "This website provides streaming media content."
shap_values = explainer([input_text])  # Pass raw text, SHAP will tokenize internally

# Visualize SHAP values
shap.plots.text(shap_values[0])